const Constants =  {
    COMMON:{
        DELETE_PHOTO:'COMMON_DELETE_PHOTO',
        UPDATE_PHOTO_CAPTION:'COMMON_UPDATE_PHOTO_CAPTION',
        UPDATE_PHOTO_TAG:'UPDATE_TOGGLE_PHOTO_TAG'

    },
    USER:{
        CREATE_USER:'USER_CREATE_USER',
        FAVORITE:'USER_FAVORITE',
        UNFAVORITE:'USER_UNFAVORITE',
        DELETE_USER:'USER_DELETE_USER'
    },
    ME:{
        UPDATE_MAIN_PHOTO:'ME_UPDATE_MAIN_PHOTO',
        ADD_PHOTO:'ME_ADD_PHOTO',
        UPLOADING_PHOTO:'ME_UPLOADING_PHOTO',
        UPLOADED_PHOTO:'ME_UPLOADED_PHOTO',
        CHANGE_PROFILE_PHOTO:'ME_CHANGE_PROFILE_PHOTO',
        SAVE_QUESTION:'ME_SAVE_QUESTION',
        SAVE_DETAIL:'ME_SAVE_DETAIL',
        UPDATE_USERSRATUS:"UPDATE_USERSRATUS"
    },
    HEADER:{
        HIGHLIGHT_TAB:"HEADER_HIGHLIGHT_TAB",
        SHOW_EVENTS:"SHOW_EVENTS"
    },
    CHAT: {
    	SHOW_INBOX : 'CHAT_SHOW_INBOX',
    	SHOW_OUTBOX : 'CHAT_SHOW_OUTBOX',
        ENABLE_MOBILE_VIEW : 'ENABLE_MOBILE_VIEW',
        DISABLE_MOBILE_VIEW : 'DISABLE_MOBILE_VIEW',
        SET_CURRENT_PEER : 'SET_CURRENT_PEER',
        SLIM_CONVERSATION_PANEL : 'SLIM_CONVERSATION_PANEL',
        FATTEN_CONVERSATION_PANEL : 'FATTEN_CONVERSATION_PANEL',
        CLEAN_INPUT : 'CLEAN_INPUT',
        DIRTY_INPUT : 'DIRTY_INPUT',
        REQUEST_INBOX_PEERS : 'REQUEST_INBOX_PEERS',
        REQUEST_OUTBOX_PEERS : 'REQUEST_OUTBOX_PEERS',
        RECEIVE_INBOX_PEERS : 'RECEIVE_INBOX_PEERS',
        RECEIVE_OUTBOX_PEERS : 'RECEIVE_OUTBOX_PEERS',
        REQUEST_MESSAGES : 'REQUEST_MESSAGES',
        RECEIVE_MESSAGES : 'RECEIVE_MESSAGES',
        RECEIVE_MESSAGE : 'RECEIVE_MESSAGE',
        CLEAR_UNREAD_COUNT : 'CLEAR_UNREAD_COUNT',
        SEND_MESSAGE_REQUEST : 'SEND_MESSAGE_REQUEST',
        SEND_MESSAGE_SUCCESS : 'SEND_MESSAGE_SUCCESS',
        ENABLE_EDIT_MODE : 'ENABLE_EDIT_MODE',
        DISABLE_EDIT_MODE : 'DISABLE_EDIT_MODE',
        SELECT_PEER : 'SELECT_PEER',
        DESELECT_PEER : 'DESELECT_PEER',
        REMOVE_PEER : 'REMOVE_PEER',
        ADD_PEER_TO_STATE : 'ADD_PEER_TO_STATE',
        ENABLE_LITE_VIEW : 'ENABLE_LITE_VIEW',
        DISABLE_LITE_VIEW : 'DISABLE_LITE_VIEW',
        SET_WINDOW_HEIGHT : 'SET_WINDOW_HEIGHT',
        SHIFT_PEER_TO_TOP : 'SHIFT_PEER_TO_TOP',
        SHIFT_PEER_TO_TOP_OF_INBOX : 'SHIFT_PEER_TO_TOP_OF_INBOX',
        SET_TOTAL_UNREAD_COUNT : 'SET_TOTAL_UNREAD_COUNT',
        CLEAR_CURRENT_PEER : 'CLEAR_CURRENT_PEER',
        DISPLAY_CONVERSATIONS_PANEL: 'DISPLAY_CONVERSATIONS_PANEL',
        HIDE_CONVERSATIONS_PANEL: 'HIDE_CONVERSATIONS_PANEL',
        DISPLAY_MESSAGES_PANEL: 'DISPLAY_MESSAGES_PANEL',
        HIDE_MESSAGES_PANEL: 'HIDE_MESSAGES_PANEL'
    },
    CHAT_LITE:{
        LOAD_LITE_VIEW: 'LOAD_LITE_VIEW',
        SHOW_LITE_VIEW: 'SHOW_LITE_VIEW',
        HIDE_LITE_VIEW: 'HIDE_LITE_VIEW',
    },
    CONNECTIONS:{
        CREATE_VISITORS:'CONNECTIONS_CREATE_VISITORS',
        CREATE_VISITED:'CONNECTIONS_CREATE_VISITED',
        CREATE_FAVORITED:'CONNECTIONS_CREATE_FAVORITED',
        CREATE_FAVORITEDME:'CONNECTIONS_CREATE_FAVORITEDME',
        SHOW_USER:'CONNECTIONS_SHOW_USER',
        DESTROY_SEARCH_USER:'CONNECTIONS_DESTROY_SEARCH_USER',
        QUICK_VIEW:'CONNECTIONS_QUICK_VIEW',
        LOAD_DATA:"LOAD_DATA"
    },
    SEARCH:{
        SHOW_USER:'SEARCH_SHOW_USER',
        DESTROY_SEARCH_USER:'SEARCH_DESTROY_SEARCH_USER',
        QUICK_VIEW:'SEARCH_QUICK_VIEW',
        SEARCH_CRITERIAS:'SEARCH_CRITERIAS',
        USED_MULTI_CRITERIAS:'SEARCH_USED_MULTI_CRITERIAS',
        SEARCH_RESULT:'SEARCH_RESULT'
    },
    LIGHTBOX:{
        OPEN:'LIGHTBOX_OPEN',
        CLOSE:'LIGHTBOX_CLOSE',
        SET_INDEX:'LIGHTBOX_SET_INDEX'
    },
    REPORT_USER:{
        OPEN: 'OPEN_REPORT_MODAL',
        CLOSE: 'CLOSE_REPORT_MODAL',
        SELECT: 'SELECT_REPORT_REASON',
        UNSELECT: 'UNSELECT_REPORT_REASON',
        START_PROCESSING: 'START_PROCESSING',
        SUCCESS: 'REPORT_USER_SUCCESS',
        FAILURE: 'REPORT_USER_FAILURE',
        RESET: 'RESET_USER_REPORT_SELECTION'
    },
    BLOCK_USER:{
      OPEN_MODAL: 'BLOCK_USER_OPEN_MODAL',
      CLOSE_MODAL: 'BLOCK_USER_CLOSE_MODAL'
    },
    EVENTS:{
        GET_EVENTS:'EVENTS_GET_EVENTS',
        GET_DETAIL:'EVENTS_GET_DETAIL',
        GET_PAST_EVENT:'EVENTS_GET_PAST_EVENT',
        SET_MOBILE_DETAIL:'EVENTS_SET_MOBILE_DETAIL'
    },
    HOME:{
        CREATE_FEEDS:'HOME_CREATE_FEEDS',
        GET_FEEDS:'HOME_GET_FEEDS',
        GET_EVENTS:'HOME_GET_EVENTS'
    }
}
export default Constants;
