
export function getPhotoTags(locale) {
    var data = {
    "en":['Cute','Confident','Stylish','Sweet','Energetic','Sexy'],
    "zh-CN":['可爱','自信','有型','甜美','活泼','性感'],
    "zh-TW":['可爱','自信','有型','甜美','活泼','性感'],
    }
   return data[locale].map(function(name,index){
        return {
            index:index,
            name:name,
            count:0,
            marked:false
        }
    });
}
export var looking_opts = {
    en: [
        {value: "1", label: 'Looking for a man'},
        {value: "2", label: 'Looking for a woman'}
    ],
    "zh-CN":[
        {value: "1", label: '寻找男'},
        {value: "2", label: '寻找女'}
    ],
    "zh-TW":[
        {value: "1", label: '寻找男'},
        {value: "2", label: '寻找女'}
    ]
};
export var gender_opts = {
    en:[
        { value: "1", label: 'Male' },
        { value: "2", label: 'Female' }
    ],
    "zh-CN":[
        { value: "1", label: '男' },
        { value: "2", label: '女' }
    ],
    "zh-TW":[
        { value: "1", label: '男' },
        { value: "2", label: '女' }
    ]
};

export var gender=["Male","Female"];

export var state_opts =[
    {value: "AL", label: "Alabama"},
    {value: "AK", label: "Alaska"},
    {value: "AZ", label: "Arizona"},
    {value: "AR", label: "Arkansas"},
    {value: "CA", label: "California"}
];

export var sign_opts = {
    en:[
        {value:  1, label: "Capricorn"},
        {value:  2, label: "Aquarius"},
        {value:  3, label: "Pisces"},
        {value:  4, label: "Aries"},
        {value:  5, label: "Taurus"},
        {value:  6, label: "Gemini"},
        {value:  7, label: "Cancer"},
        {value:  8, label: "Leo"},
        {value:  9, label: "Virgo"},
        {value:  10, label: "Libra"},
        {value:  11, label: "Scorpio"},
        {value: 12, label: "Sagittarius"}
    ],
    "zh-CN":[
        {value:  1, label: "摩羯"},
        {value:  2, label: "水瓶"},
        {value:  3, label: "双鱼"},
        {value:  4, label: "白羊"},
        {value:  5, label: "金牛"},
        {value:  6, label: "双子"},
        {value:  7, label: "巨蟹"},
        {value:  8, label: "狮子"},
        {value:  9, label: "处女"},
        {value:  10, label: "天秤"},
        {value:  11, label: "天蝎"},
        {value: 12, label: "射手"}
    ],
    "zh-TW":[
        {value:  1, label: "摩羯"},
        {value:  2, label: "水瓶"},
        {value:  3, label: "雙魚"},
        {value:  4, label: "白羊"},
        {value:  5, label: "金牛"},
        {value:  6, label: "雙子"},
        {value:  7, label: "巨蟹"},
        {value:  8, label: "狮子"},
        {value:  9, label: "處女"},
        {value:  10, label: "天秤"},
        {value:  11, label: "天蠍"},
        {value: 12, label: "射手"}
    ]
};


export var zodiac_opts = [
    {value: 1, label: "Rat"},
    {value: 2, label: "Ox"},
    {value: 3, label: "Tiger"},
    {value: 4, label: "Rabbit"},
    {value: 5, label: "Dragon"},
    {value: 6, label: "Snake"},
    {value: 7, label: "Horse"},
    {value: 8, label: "Sheep"},
    {value: 9, label: "Monkey"},
    {value: 10, label: "Rooster"},
    {value: 11, label: "Dog"},
    {value:12, label: "Boar"}
];

export var cons_opts = {
    "zodiac":[],
    "chinese_zodiac":[],
    "body_type":[],
    "marital_status":[],
    "drinking":[],
    "smoking":[],
    "languages":[],
    'immigration':[],
    "interests":[],
    "income":[],
    "education":[],
    "have_children":[],
    "occupation":[],
    "ethnicity":[],
    "religion":[]
};

export var cons_opt_vals = {
    "zodiac":[],
    "chinese_zodiac":[],
    "body_type":[],
    "marital_status":[],
    "drinking":[],
    "smoking":[],
    "languages":[],
    'immigration':[],
    "interests":[],
    "income":[],
    "occupation":[],
    "education":[],
    "have_children":[],
    "ethnicity":[],
    "religion":[]
};

export var birthplace_opts = [
    {value: 1, label: "China"},
    {value: 2, label: "Taiwan"},
    {value: 3, label: "Hong Kong"},
    {value: 4, label: "USA"},
    {value: 5, label: "Canada"},
    {value: 6, label: "Other"}
];

export var country_other_opts = {
    en:[
        { label: "United States", value:1},
        { label: "Canada", value:5},
        { label: "China", value:2},
        { label: "HongKong", value:3},
        { label: "Taiwan", value:4},
        { label: "Macao", value:195},
        { label: "United Kingdom", value:185},
        { label: "France", value:64},
        { label: "Germany", value:68},
        { label: "Australia", value:14},
        { label: "New Zealand", value:128},
        { label: "Japan", value:88},
        { label: "Singapore", value:158},
        { label: "Malaysia", value:109},
        { label: "Indonesia", value:81},
        {value: 6, label: "Other"}
    ],
    "zh-CN":[
        { label: "美国", value:1},
        { label: "加拿大", value:5},
        { label: "大陆", value:2},
        { label: "香港", value:3},
        { label: "台湾", value:4},
        { label: "澳门", value:195},
        { label: "英国", value:185},
        { label: "法国", value:64},
        { label: "德国", value:68},
        { label: "澳大利亚", value:14},
        { label: "新西兰", value:128},
        { label: "日本", value:88},
        { label: "新加坡", value:158},
        { label: "马来西亚", value:109},
        { label: "印度尼西亚", value:81},
        {value: 6, label: "其他"}
    ],
    "zh-TW":[
        { label: "美国", value:1},
        { label: "加拿大", value:5},
        { label: "大陆", value:2},
        { label: "香港", value:3},
        { label: "台湾", value:4},
        { label: "澳门", value:195},
        { label: "英国", value:185},
        { label: "法国", value:64},
        { label: "德国", value:68},
        { label: "澳大利亚", value:14},
        { label: "新西兰", value:128},
        { label: "日本", value:88},
        { label: "新加坡", value:158},
        { label: "马来西亚", value:109},
        { label: "印度尼西亚", value:81},
        {value: 6, label: "其他"}
    ]
};

export var faith_opts = [
    {value: 1, label: "Non-Religious"},
    {value: 2, label: "Buddhism"},
    {value: 3, label: "Christian"},
    {value: 4, label: "Islam"},
    {value: 5, label: "MultiControls"}
];

export var height_opts = {
    en:[
        {value: "110", label: "3'7\""},
        {value: "120", label: "3'11\""},
        {value: "125", label: "4'1\""},
        {value: "130", label: "4'3\""},
        {value: "135", label: "4'5\""},
        {value: "140", label: "4'7\""},
        {value: "145", label: "4'9\""},
        {value: "150", label: "4'11\""},
        {value: "155", label: "5'1\""},
        {value: "158", label: "5'2\""},
        {value: "160", label: "5'3\""},
        {value: "162", label: "5'4\""},
        {value: "165", label: "5'5\""},
        {value: "168", label: "5'6\""},
        {value: "170", label: "5'7\""},
        {value: "172", label: "5'8\""},
        {value: "175", label: "5'9\""},
        {value: "178", label: "5'10\""},
        {value: "180", label: "5'11\""},
        {value: "185", label: "6'1\""},
        {value: "190", label: "6'3\""},
        {value: "195", label: "6'5\""},
        {value: "205", label: "6'9\""},
        {value: "210", label: "6'11\""},
        {value: "215", label: "7'1\""},
        {value: "220", label: "7'3\""},
        {value: "225", label: "7'5\""},
        {value: "230", label: "7'7\""},
        {value: "235", label: "7'9\""},
        {value: "240", label: "7'11\""},
        {value: "250", label: "8'3\""},
        {value: "260", label: "8'6\""},
        {value: "270", label: "8'10\""}
    ],
    "zh-CN":[
        {value: "110", label: "110cm"},
        {value: "120", label: "120cm"},
        {value: "125", label: "125cm"},
        {value: "130", label: "130cm"},
        {value: "135", label: "135cm"},
        {value: "140", label: "140cm"},
        {value: "145", label: "145cm"},
        {value: "150", label: "150cm"},
        {value: "155", label: "155cm"},
        {value: "158", label: "158cm"},
        {value: "160", label: "160cm"},
        {value: "162", label: "162cm"},
        {value: "165", label: "165cm"},
        {value: "168", label: "168cm"},
        {value: "170", label: "170cm"},
        {value: "172", label: "172cm"},
        {value: "175", label: "175cm"},
        {value: "178", label: "178cm"},
        {value: "180", label: "180cm"},
        {value: "185", label: "185cm"},
        {value: "190", label: "190cm"},
        {value: "195", label: "195cm"},
        {value: "205", label: "205cm"},
        {value: "210", label: "210cm"},
        {value: "215", label: "215cm"},
        {value: "220", label: "220cm"},
        {value: "225", label: "225cm"},
        {value: "230", label: "230cm"},
        {value: "235", label: "235cm"},
        {value: "240", label: "240cm"},
        {value: "250", label: "250cm"},
        {value: "260", label: "260cm"},
        {value: "270", label: "270cm"}
    ],
    "zh-TW":[
        {value: "110", label: "110cm"},
        {value: "120", label: "120cm"},
        {value: "125", label: "125cm"},
        {value: "130", label: "130cm"},
        {value: "135", label: "135cm"},
        {value: "140", label: "140cm"},
        {value: "145", label: "145cm"},
        {value: "150", label: "150cm"},
        {value: "155", label: "155cm"},
        {value: "158", label: "158cm"},
        {value: "160", label: "160cm"},
        {value: "162", label: "162cm"},
        {value: "165", label: "165cm"},
        {value: "168", label: "168cm"},
        {value: "170", label: "170cm"},
        {value: "172", label: "172cm"},
        {value: "175", label: "175cm"},
        {value: "178", label: "178cm"},
        {value: "180", label: "180cm"},
        {value: "185", label: "185cm"},
        {value: "190", label: "190cm"},
        {value: "195", label: "195cm"},
        {value: "205", label: "205cm"},
        {value: "210", label: "210cm"},
        {value: "215", label: "215cm"},
        {value: "220", label: "220cm"},
        {value: "225", label: "225cm"},
        {value: "230", label: "230cm"},
        {value: "235", label: "235cm"},
        {value: "240", label: "240cm"},
        {value: "250", label: "250cm"},
        {value: "260", label: "260cm"},
        {value: "270", label: "270cm"}
    ]
};

export var age_arrived_opts = [
];

for(var i = 1;i<81;i++){
    age_arrived_opts.push({value:i,label:i});
}

export var year_opts = [
];
var curYear =  new Date();
var year = curYear.getFullYear() - 18;
for(var i = year; i>year-80; i--){
    year_opts.push({value:i,label:i});
};

export var month_opts = [
];
for(var i = 1; i<=12; i++){
    month_opts.push({value:i,label:i});
};

export var day_opts = [
];
for(var i = 1; i<=31; i++){
    day_opts.push({value:i,label:i});
};

export var age_opts = [
];

for(var i = 18;i<81;i++){
    age_opts.push({value:i,label:i});
}

export var sort_opts = {
    en:[
    {value: "ascend_by_distance", label: "Distance"},
    {value: "descend_by_last_request_at", label: "Active"},
    {value: "descend_by_charm_discounted", label: "Charm"}
    ],
    "zh-CN":[
        {value: "ascend_by_distance", label: "距离"},
        {value: "descend_by_last_request_at", label: "活跃"},
        {value: "descend_by_charm_discounted", label: "魅力"}
    ],
    "zh-TW":[
        {value: "ascend_by_distance", label: "距离"},
        {value: "descend_by_last_request_at", label: "活跃"},
        {value: "descend_by_charm_discounted", label: "魅力"}
    ]
};

export var states = {
    "1": [{label:"Alabama",value: "AL"},
        { label:"Alaska", value:"AK"},
        { label:"Arizona", value:"AZ"},
        { label:"Arkansas", value:"AR"},
        { label:"California", value: "CA"},
        { label:"Colorado", value: "CO"},
        { label:"Connecticut", value: "CT"},
        { label:"Delaware", value: "DE"},
        { label:"District of Columbia", value: "DC"},
        { label:"Florida", value: "FL"},
        { label:"Georgia", value: "GA"},
        { label:"Hawaii", value: "HI"},
        { label:"Idaho", value: "ID"},
        { label:"Illinois", value: "IL"},
        { label:"Indiana", value: "IN"},
        { label:"Iowa", value: "IA"},
        { label:"Kansas", value: "KS"},
        { label:"Kentucky", value: "KY"},
        { label:"Louisiana", value: "LA"},
        { label:"Maine", value: "ME"},
        { label:"Maryland", value: "MD"},
        { label:"Massachusetts", value: "MA"},
        { label:"Michigan", value: "MI"},
        { label:"Minnesota", value: "MN"},
        { label:"Mississippi", value: "MS"},
        { label:"Missouri", value: "MO"},
        { label:"Montana", value: "MT"},
        { label:"Nebraska", value: "NE"},
        { label:"Nevada", value: "NV"},
        { label:"New Hampshire", value: "NH"},
        { label:"New Jersey", value: "NJ"},
        { label:"New Mexico", value: "NM"},
        { label:"New York", value: "NY"},
        { label:"North Carolina", value: "NC"},
        { label:"North Dakota", value: "ND"},
        { label:"Ohio", value: "OH"},
        { label:"Oklahoma", value: "OK"},
        { label:"Oregon", value: "OR"},
        { label:"Pennsylvania", value: "PA"},
        { label:"Puerto Rico", value: "PR"},
        { label:"Rhode Island", value: "RI"},
        { label:"South Carolina", value: "SC"},
        { label:"South Dakota", value: "SD"},
        { label:"Tennessee", value: "TN"},
        { label:"Texas", value: "TX"},
        { label:"Utah", value: "UT"},
        { label:"Vermont", value: "VT"},
        { label:"Virgin Islands", value: "VI"},
        { label:"Virginia", value: "VA"},
        { label:"Washington", value: "WA"},
        { label:"West Virginia", value: "WV"},
        { label:"Wisconsin", value: "WI"},
        { label:"Wyoming", value: "WY"}],
    "5": [{ label:"Alberta", value: "AB"},
        { label:"British Columbia", value: "BC"},
        { label:"Manitoba", value: "MB"},
        { label:"New Brunswick", value: "NB"},
        { label:"Newfoundland and Labrador", value: "NL"},
        { label:"Northwest Territories", value: "NT"},
        { label:"Nova Scotia", value: "NS"},
        { label:"Nunavut", value: "NU"},
        { label:"Ontario", value: "ON"},
        { label:"Prince Edward Island", value: "PE"},
        { label:"Quebec", value: "QC"},
        { label:"Saskatchewan", value: "SK"},
        { label:"Yukon", value: "YT"}],
    "185":[{ label:"England", value: "ENG"},
        { label:"Northern Ireland", value: "NIR"},
        { label:"Scotland", value: "SCT"},
        { label:"Wales", value: "WLS"}],
    "64":[{ label:"Aquitaine", value: "97"},
        { label:"Auvergne", value: "98"},
        { label:"Basse-Normandie", value: "99"},
        { label:"Bourgogne", value: "A1"},
        { label:"Bretagne", value: "A2"},
        { label:"Centre", value: "A3"},
        { label:"Champagne-Ardenne", value: "A4"},
        { label:"Corse", value: "A5"},
        { label:"Franche-Comte", value: "A6"},
        { label:"Haute-Normandie", value: "A7"},
        { label:"Ile-de-France", value: "A8"},
        { label:"Languedoc-Roussillon", value: "A9"},
        { label:"Limousin", value: "B1"},{ label:"Lorraine", value: "B2"},
        { label:"Midi-Pyrenees", value: "B3"},
        { label:"Nord-Pas-de-Calais", value: "B4"},
        { label:"Pays de la Loire", value: "B5"},
        { label:"Picardie", value: "B6"},
        { label:"Poitou-Charentes", value: "B7"},
        { label:"Provence-Alpes-Cote d'Azur", value: "B8"},
        { label:"Rhone-Alpes", value: "B9"},
        { label:"Alsace", value: "C1"}],
    "68":[{ label:"Baden-Wurttemberg", value: "BW"},
        { label:"Bayern", value: "BY"},
        { label:"Bremen", value: "HB"},
        { label:"Hamburg", value: "HH"},
        { label:"Hessen", value: "HE"},
        { label:"Niedersachsen", value: "NI"},
        { label:"Nordrhein-Westfalen", value: "NW"},
        { label:"Rheinland-Pfalz", value: "RP"},
        { label:"Saarland", value: "SL"},
        { label:"Schleswig-Holstein", value: "SH"},
        { label:"Brandenburg", value: "BB"},
        { label:"Mecklenburg-Vorpommern", value: "MV"},
        { label:"Sachsen", value: "SN"},
        { label:"Sachsen-Anhalt", value: "ST"},
        { label:"Thuringen", value: "TH"},
        { label:"Berlin", value: "BE"}],
    "14":[{ label:"Australian Capital Territory", value: "ACT"},
        { label:"New South Wales", value: "NSW"},
        { label:"Northern Territory", value: "NT"},
        { label:"Queensland", value: "QLD"},
        { label:"South Australia", value: "SA"},
        { label:"Tasmania", value: "TAS"},
        { label:"Victoria", value: "VIC"},
        { label:"Western Australia", value: "WA"}],
    "128":[{ label:"Northland", value: "NTL"},
        { label:"Auckland", value: "AUK"},
        { label:"Waikato", value: "WKO"},
        { label:"Bay of Plenty", value: "BOP"},
        { label:"Gisborne", value: "GIS"},
        { label:"Hawke's Bay", value: "HKB"},
        { label:"Taranaki", value: "TKI"},
        { label:"Manawatu-Wanganui", value: "MWT"},
        { label:"Wellington", value: "WGN"},
        { label:"Tasman", value: "TAS"},
        { label:"Nelson", value: "NSN"},
        { label:"Marlborough", value: "MBH"},
        { label:"West Coast", value: "WTC"},
        { label:"Canterbury", value: "CAN"},
        { label:"Otago", value: "OTA"},
        { label:"Southland", value: "STL"}]
};

export var country_opts={
    en:[
        { label: "United States", value:1},
        { label: "Canada", value:5},
        { label: "China", value:2},
        { label: "HongKong", value:3},
        { label: "Taiwan", value:4},
        { label: "Macao", value:195},
        { label: "United Kingdom", value:185},
        { label: "France", value:64},
        { label: "Germany", value:68},
        { label: "Australia", value:14},
        { label: "New Zealand", value:128},
        { label: "Japan", value:88},
        { label: "Singapore", value:158},
        { label: "Malaysia", value:109},
        { label: "Indonesia", value:81},
        { label: "Vietnam", value:191},
        { label: "Thailand", value:174},
        { label: "Philippines", value:140},
        { label: "Afghanistan", value:6},
        { label: "Albania", value:7},
        { label: "Algeria", value:8},
        { label: "Andorra", value:9},
        { label: "Angola", value:10},
        { label: "Antigua and Barbuda", value:11},
        { label: "Argentina", value:12},
        { label: "Armenia", value:13},
        { label: "Austria", value:15},
        { label: "Azerbaijan", value:16},
        { label: "Bahamas", value:17},
        { label: "Bahrain", value:18},
        { label: "Bangladesh", value:19},
        { label: "Barbados", value:20},
        { label: "Belarus", value:21},
        { label: "Belgium", value:22},
        { label: "Belize", value:23},
        { label: "Benin", value:24},
        { label: "Bhutan", value:25},
        { label: "Bolivia", value:26},
        { label: "Bosnia and Herzegovina", value:27},
        { label: "Botswana", value:28},
        { label: "Brazil", value:29},
        { label: "Brunei", value:30},
        { label: "Bulgaria", value:31},
        { label: "Burkina Faso", value:32},
        { label: "Burundi", value:33},
        { label: "Cambodia", value:34},
        { label: "Cameroon", value:35},
        { label: "Cape Verde", value:36},
        { label: "Central African Republic", value:37},
        { label: "Chad", value:38},
        { label: "Chile", value:39},
        { label: "Colombia", value:40},
        { label: "Comoros", value:41},
        { label: "Congo (Brazzaville)", value:42},
        { label: "Congo", value:43},
        { label: "Costa Rica", value:44},
        { label: "Cote d'Ivoire", value:45},
        { label: "Croatia", value:46},
        { label: "Cuba", value:47},
        { label: "Cyprus", value:48},
        { label: "Czech Republic", value:49},
        { label: "Denmark", value:50},
        { label: "Djibouti", value:51},
        { label: "Dominica", value:52},
        { label: "Dominican Republic", value:53},
        { label: "East Timor (Timor Timur)", value:54},
        { label: "Ecuador", value:55},
        { label: "Egypt", value:56},
        { label: "El Salvador", value:57},
        { label: "Equatorial Guinea", value:58},
        { label: "Eritrea", value:59},
        { label: "Estonia", value:60},
        { label: "Ethiopia", value:61},
        { label: "Fiji", value:62},
        { label: "Finland", value:63},
        { label: "Gabon", value:65},
        { label: "Gambia, The", value:66},
        { label: "Georgia", value:67},
        { label: "Ghana", value:69},
        { label: "Greece", value:70},
        { label: "Grenada", value:71},
        { label: "Guatemala", value:72},
        { label: "Guinea", value:73},
        { label: "Guinea-Bissau", value:74},
        { label: "Guyana", value:75},
        { label: "Haiti", value:76},
        { label: "Honduras", value:77},
        { label: "Hungary", value:78},
        { label: "Iceland", value:79},
        { label: "India", value:80},
        { label: "Iran", value:82},
        { label: "Iraq", value:83},
        { label: "Ireland", value:84},
        { label: "Israel", value:85},
        { label: "Italy", value:86},
        { label: "Jamaica", value:87},
        { label: "Jordan", value:89},
        { label: "Kazakhstan", value:90},
        { label: "Kenya", value:91},
        { label: "Kiribati", value:92},
        { label: "Korea, North", value:93},
        { label: "Korea, South", value:94},
        { label: "Kuwait", value:95},
        { label: "Kyrgyzstan", value:96},
        { label: "Laos", value:97},
        { label: "Latvia", value:98},
        { label: "Lebanon", value:99},
        { label: "Lesotho", value:100},
        { label: "Liberia", value:101},
        { label: "Libya", value:102},
        { label: "Liechtenstein", value:103},
        { label: "Lithuania", value:104},
        { label: "Luxembourg", value:105},
        { label: "Macedonia", value:106},
        { label: "Madagascar", value:107},
        { label: "Malawi", value:108},
        { label: "Maldives", value:110},
        { label: "Mali", value:111},
        { label: "Malta", value:112},
        { label: "Marshall Islands", value:113},
        { label: "Mauritania", value:114},
        { label: "Mauritius", value:115},
        { label: "Mexico", value:116},
        { label: "Micronesia", value:117},
        { label: "Moldova", value:118},
        { label: "Monaco", value:119},
        { label: "Mongolia", value:120},
        { label: "Morocco", value:121},
        { label: "Mozambique", value:122},
        { label: "Myanmar", value:123},
        { label: "Namibia", value:124},
        { label: "Nauru", value:125},
        { label: "Nepal", value:126},
        { label: "Netherlands", value:127},
        { label: "Nicaragua", value:129},
        { label: "Niger", value:130},
        { label: "Nigeria", value:131},
        { label: "Norway", value:132},
        { label: "Oman", value:133},
        { label: "Pakistan", value:134},
        { label: "Palau", value:135},
        { label: "Panama", value:136},
        { label: "Papua New Guinea", value:137},
        { label: "Paraguay", value:138},
        { label: "Peru", value:139},
        { label: "Poland", value:141},
        { label: "Portugal", value:142},
        { label: "Qatar", value:143},
        { label: "Romania", value:144},
        { label: "Russia", value:145},
        { label: "Rwanda", value:146},
        { label: "Saint Kitts and Nevis", value:147},
        { label: "Saint Lucia", value:148},
        { label: "Saint Vincent", value:149},
        { label: "Samoa", value:150},
        { label: "San Marino", value:151},
        { label: "Sao Tome and Principe", value:152},
        { label: "Saudi Arabia", value:153},
        { label: "Senegal", value:154},
        { label: "Serbia and Montenegro", value:155},
        { label: "Seychelles", value:156},
        { label: "Sierra Leone", value:157},
        { label: "Slovakia", value:159},
        { label: "Slovenia", value:160},
        { label: "Solomon Islands", value:161},
        { label: "Somalia", value:162},
        { label: "South Africa", value:163},
        { label: "Spain", value:164},
        { label: "Sri Lanka", value:165},
        { label: "Sudan", value:166},
        { label: "Suriname", value:167},
        { label: "Swaziland", value:168},
        { label: "Sweden", value:169},
        { label: "Switzerland", value:170},
        { label: "Syria", value:171},
        { label: "Tajikistan", value:172},
        { label: "Tanzania", value:173},
        { label: "Togo", value:175},
        { label: "Tonga", value:176},
        { label: "Trinidad and Tobago", value:177},
        { label: "Tunisia", value:178},
        { label: "Turkey", value:179},
        { label: "Turkmenistan", value:180},
        { label: "Tuvalu", value:181},
        { label: "Uganda", value:182},
        { label: "Ukraine", value:183},
        { label: "United Arab Emirates", value:184},
        { label: "Uruguay", value:186},
        { label: "Uzbekistan", value:187},
        { label: "Vanuatu", value:188},
        { label: "Vatican City", value:189},
        { label: "Venezuela", value:190},
        { label: "Yemen", value:192},
        { label: "Zambia", value:193},
        { label: "Zimbabwe", value:194}
    ],
    "zh-CN":[
        { label: "美国", value:1},
        { label: "加拿大", value:5},
        { label: "中国", value:2},
        { label: "香港", value:3},
        { label: "台湾", value:4},
        { label: "澳门", value:195},
        { label: "英国", value:185},
        { label: "法国", value:64},
        { label: "德国", value:68},
        { label: "澳大利亚", value:14},
        { label: "新西兰", value:128},
        { label: "日本", value:88},
        { label: "新加坡", value:158},
        { label: "马来西亚", value:109},
        { label: "印度尼西亚", value:81},
        { label: "越南", value:191},
        { label: "泰国", value:174},
        { label: "菲律宾", value:140},
        { label: "阿富汗", value:6},
        { label: "阿尔巴尼亚", value:7},
        { label: "阿尔及利亚", value:8},
        { label: "安道尔", value:9},
        { label: "安哥拉", value:10},
        { label: "安提瓜和巴布达", value:11},
        { label: "阿根廷", value:12},
        { label: "亚美尼亚", value:13},
        { label: "奥地利", value:15},
        { label: "阿塞拜疆", value:16},
        { label: "巴哈马", value:17},
        { label: "巴林", value:18},
        { label: "孟加拉国", value:19},
        { label: "巴巴多斯", value:20},
        { label: "白俄罗斯", value:21},
        { label: "比利时", value:22},
        { label: "伯利兹", value:23},
        { label: "贝宁", value:24},
        { label: "不丹", value:25},
        { label: "玻利维亚", value:26},
        { label: "波斯尼亚和黑塞哥维那", value:27},
        { label: "博茨瓦纳", value:28},
        { label: "巴西", value:29},
        { label: "文莱", value:30},
        { label: "保加利亚", value:31},
        { label: "布基纳法索", value:32},
        { label: "布隆迪", value:33},
        { label: "柬埔寨", value:34},
        { label: "喀麦隆", value:35},
        { label: "佛得角", value:36},
        { label: "中非共和国", value:37},
        { label: "乍得", value:38},
        { label: "智利", value:39},
        { label: "哥伦比亚", value:40},
        { label: "科摩罗", value:41},
        { label: "刚果（布）", value:42},
        { label: "刚果", value:43},
        { label: "哥斯达黎加", value:44},
        { label: "科特迪瓦", value:45},
        { label: "克罗地亚", value:46},
        { label: "古巴", value:47},
        { label: "塞浦路斯", value:48},
        { label: "捷克共和国", value:49},
        { label: "丹麦", value:50},
        { label: "吉布提", value:51},
        { label: "多米尼加", value:52},
        { label: "多米尼加共和国", value:53},
        { label: "东帝汶（东帝汶帖木儿）", value:54},
        { label: "厄瓜多尔", value:55},
        { label: "埃及", value:56},
        { label: "萨尔瓦多", value:57},
        { label: "赤道几内亚", value:58},
        { label: "厄立特里亚", value:59},
        { label: "爱沙尼亚", value:60},
        { label: "埃塞俄比亚", value:61},
        { label: "斐济", value:62},
        { label: "芬兰", value:63},
        { label: "加蓬", value:65},
        { label: "冈比亚", value:66},
        { label: "乔治亚", value:67},
        { label: "加纳", value:69},
        { label: "希腊", value:70},
        { label: "格林纳达", value:71},
        { label: "危地马拉", value:72},
        { label: "几内亚", value:73},
        { label: "几内亚比绍", value:74},
        { label: "圭亚那", value:75},
        { label: "海地", value:76},
        { label: "洪都拉斯", value:77},
        { label: "匈牙利", value:78},
        { label: "冰岛", value:79},
        { label: "印度", value:80},
        { label: "伊朗", value:82},
        { label: "伊拉克", value:83},
        { label: "爱尔兰", value:84},
        { label: "以色列", value:85},
        { label: "意大利", value:86},
        { label: "牙买加", value:87},
        { label: "乔丹", value:89},
        { label: "卡萨斯坦", value:90},
        { label: "肯尼亚", value:91},
        { label: "基里巴斯", value:92},
        { label: "朝鲜", value:93},
        { label: "韩国", value:94},
        { label: "科威特", value:95},
        { label: "吉尔吉斯斯坦", value:96},
        { label: "老挝", value:97},
        { label: "拉脱维亚", value:98},
        { label: "黎巴嫩", value:99},
        { label: "莱索托", value:100},
        { label: "利比里亚", value:101},
        { label: "利比亚", value:102},
        { label: "列支敦士登", value:103},
        { label: "立陶宛", value:104},
        { label: "卢森堡", value:105},
        { label: "马其顿", value:106},
        { label: "马达加斯加", value:107},
        { label: "马拉维", value:108},
        { label: "马尔代夫", value:110},
        { label: "马里", value:111},
        { label: "马耳他", value:112},
        { label: "马歇尔群岛", value:113},
        { label: "毛里塔尼亚", value:114},
        { label: "毛里求斯", value:115},
        { label: "墨西哥", value:116},
        { label: "密克罗尼西亚", value:117},
        { label: "摩尔多瓦", value:118},
        { label: "摩纳哥", value:119},
        { label: "蒙古", value:120},
        { label: "摩洛哥", value:121},
        { label: "莫桑比克", value:122},
        { label: "缅甸", value:123},
        { label: "纳米比亚", value:124},
        { label: "瑙鲁", value:125},
        { label: "尼泊尔", value:126},
        { label: "荷兰", value:127},
        { label: "尼加拉瓜", value:129},
        { label: "尼日尔", value:130},
        { label: "尼日利亚", value:131},
        { label: "挪威", value:132},
        { label: "阿曼", value:133},
        { label: "巴基斯坦", value:134},
        { label: "帕劳", value:135},
        { label: "巴拿马", value:136},
        { label: "巴布亚新几内亚", value:137},
        { label: "巴拉圭", value:138},
        { label: "秘鲁", value:139},
        { label: "波兰", value:141},
        { label: "葡萄牙", value:142},
        { label: "卡塔尔", value:143},
        { label: "罗马尼亚", value:144},
        { label: "俄罗斯", value:145},
        { label: "卢旺达", value:146},
        { label: "圣基茨和尼维斯", value:147},
        { label: "圣露西亚", value:148},
        { label: "圣文森特", value:149},
        { label: "萨摩亚", value:150},
        { label: "圣马力诺", value:151},
        { label: "圣多美和普林西比", value:152},
        { label: "沙特阿拉伯", value:153},
        { label: "塞内加尔", value:154},
        { label: "塞尔维亚和黑山", value:155},
        { label: "塞舌尔", value:156},
        { label: "塞拉利昂", value:157},
        { label: "斯洛伐克", value:159},
        { label: "斯洛文尼亚", value:160},
        { label: "所罗门群岛", value:161},
        { label: "索马里", value:162},
        { label: "南非", value:163},
        { label: "西班牙", value:164},
        { label: "斯里兰卡", value:165},
        { label: "苏丹", value:166},
        { label: "苏里南", value:167},
        { label: "斯威士兰", value:168},
        { label: "瑞典", value:169},
        { label: "瑞士", value:170},
        { label: "叙利亚", value:171},
        { label: "塔吉克斯坦", value:172},
        { label: "坦桑尼亚", value:173},
        { label: "多哥", value:175},
        { label: "汤加", value:176},
        { label: "特立尼达和多巴哥", value:177},
        { label: "突尼斯", value:178},
        { label: "土耳其", value:179},
        { label: "土库曼斯坦", value:180},
        { label: "图瓦卢", value:181},
        { label: "乌干达", value:182},
        { label: "乌克兰", value:183},
        { label: "阿拉伯联合酋长国", value:184},
        { label: "乌拉圭", value:186},
        { label: "乌兹别克斯坦", value:187},
        { label: "瓦努阿图", value:188},
        { label: "梵蒂冈城", value:189},
        { label: "委内瑞拉", value:190},
        { label: "也门", value:192},
        { label: "赞比亚", value:193},
        { label: "津巴布韦", value:194}
    ],
    "zh-TW":[
        { label: "美國", value:1},
        { label: "加拿大", value:5},
        { label: "中國", value:2},
        { label: "香港", value:3},
        { label: "臺灣", value:4},
        { label: "澳門", value:195},
        { label: "英國", value:185},
        { label: "法國", value:64},
        { label: "德國", value:68},
        { label: "澳大利亞", value:14},
        { label: "新西蘭", value:128},
        { label: "日本", value:88},
        { label: "新加坡", value:158},
        { label: "馬來西亞", value:109},
        { label: "印度尼西亞", value:81},
        { label: "越南", value:191},
        { label: "泰國", value:174},
        { label: "菲律賓", value:140},
        { label: "阿富汗", value:6},
        { label: "阿爾巴尼亞", value:7},
        { label: "阿爾及利亞", value:8},
        { label: "安道爾", value:9},
        { label: "安哥拉", value:10},
        { label: "安提瓜和巴布達", value:11},
        { label: "阿根廷", value:12},
        { label: "亞美尼亞", value:13},
        { label: "奧地利", value:15},
        { label: "阿塞拜疆", value:16},
        { label: "巴哈馬", value:17},
        { label: "巴林", value:18},
        { label: "孟加拉國", value:19},
        { label: "巴巴多斯", value:20},
        { label: "白俄羅斯", value:21},
        { label: "比利時", value:22},
        { label: "伯利茲", value:23},
        { label: "貝寧", value:24},
        { label: "不丹", value:25},
        { label: "玻利維亞", value:26},
        { label: "波斯尼亞和黑塞哥維那", value:27},
        { label: "博茨瓦納", value:28},
        { label: "巴西", value:29},
        { label: "文萊", value:30},
        { label: "保加利亞", value:31},
        { label: "布基納法索", value:32},
        { label: "布隆迪", value:33},
        { label: "柬埔寨", value:34},
        { label: "喀麥隆", value:35},
        { label: "佛得角", value:36},
        { label: "中非共和國", value:37},
        { label: "乍得", value:38},
        { label: "智利", value:39},
        { label: "哥倫比亞", value:40},
        { label: "科摩羅", value:41},
        { label: "剛果（布）", value:42},
        { label: "剛果", value:43},
        { label: "哥斯達黎加", value:44},
        { label: "科特迪瓦", value:45},
        { label: "克羅地亞", value:46},
        { label: "古巴", value:47},
        { label: "塞浦路斯", value:48},
        { label: "捷克共和國", value:49},
        { label: "丹麥", value:50},
        { label: "吉布提", value:51},
        { label: "多米尼加", value:52},
        { label: "多米尼加共和國", value:53},
        { label: "東帝汶（東帝汶帖木兒）", value:54},
        { label: "厄瓜多爾", value:55},
        { label: "埃及", value:56},
        { label: "薩爾瓦多", value:57},
        { label: "赤道幾內亞", value:58},
        { label: "厄立特裏亞", value:59},
        { label: "愛沙尼亞", value:60},
        { label: "埃塞俄比亞", value:61},
        { label: "斐濟", value:62},
        { label: "芬蘭", value:63},
        { label: "加蓬", value:65},
        { label: "岡比亞", value:66},
        { label: "喬治亞", value:67},
        { label: "加納", value:69},
        { label: "希臘", value:70},
        { label: "格林納達", value:71},
        { label: "危地馬拉", value:72},
        { label: "幾內亞", value:73},
        { label: "幾內亞比紹", value:74},
        { label: "圭亞那", value:75},
        { label: "海地", value:76},
        { label: "洪都拉斯", value:77},
        { label: "匈牙利", value:78},
        { label: "冰島", value:79},
        { label: "印度", value:80},
        { label: "伊朗", value:82},
        { label: "伊拉克", value:83},
        { label: "愛爾蘭", value:84},
        { label: "以色列", value:85},
        { label: "意大利", value:86},
        { label: "牙買加", value:87},
        { label: "喬丹", value:89},
        { label: "卡薩斯坦", value:90},
        { label: "肯尼亞", value:91},
        { label: "基裏巴斯", value:92},
        { label: "朝鮮", value:93},
        { label: "韓國", value:94},
        { label: "科威特", value:95},
        { label: "吉爾吉斯斯坦", value:96},
        { label: "老撾", value:97},
        { label: "拉脫維亞", value:98},
        { label: "黎巴嫩", value:99},
        { label: "萊索托", value:100},
        { label: "利比裏亞", value:101},
        { label: "利比亞", value:102},
        { label: "列支敦士登", value:103},
        { label: "立陶宛", value:104},
        { label: "盧森堡", value:105},
        { label: "馬其頓", value:106},
        { label: "馬達加斯加", value:107},
        { label: "馬拉維", value:108},
        { label: "馬爾代夫", value:110},
        { label: "馬裏", value:111},
        { label: "馬耳他", value:112},
        { label: "馬歇爾群島", value:113},
        { label: "毛裏塔尼亞", value:114},
        { label: "毛裏求斯", value:115},
        { label: "墨西哥", value:116},
        { label: "密克羅尼西亞", value:117},
        { label: "摩爾多瓦", value:118},
        { label: "摩納哥", value:119},
        { label: "蒙古", value:120},
        { label: "摩洛哥", value:121},
        { label: "莫桑比克", value:122},
        { label: "緬甸", value:123},
        { label: "納米比亞", value:124},
        { label: "瑙魯", value:125},
        { label: "尼泊爾", value:126},
        { label: "荷蘭", value:127},
        { label: "尼加拉瓜", value:129},
        { label: "尼日爾", value:130},
        { label: "尼日利亞", value:131},
        { label: "挪威", value:132},
        { label: "阿曼", value:133},
        { label: "巴基斯坦", value:134},
        { label: "帕勞", value:135},
        { label: "巴拿馬", value:136},
        { label: "巴布亞新幾內亞", value:137},
        { label: "巴拉圭", value:138},
        { label: "秘魯", value:139},
        { label: "波蘭", value:141},
        { label: "葡萄牙", value:142},
        { label: "卡塔爾", value:143},
        { label: "羅馬尼亞", value:144},
        { label: "俄羅斯", value:145},
        { label: "盧旺達", value:146},
        { label: "聖基茨和尼維斯", value:147},
        { label: "聖露西亞", value:148},
        { label: "聖文森特", value:149},
        { label: "薩摩亞", value:150},
        { label: "聖馬力諾", value:151},
        { label: "聖多美和普林西比", value:152},
        { label: "沙特阿拉伯", value:153},
        { label: "塞內加爾", value:154},
        { label: "塞爾維亞和黑山", value:155},
        { label: "塞舌爾", value:156},
        { label: "塞拉利昂", value:157},
        { label: "斯洛伐克", value:159},
        { label: "斯洛文尼亞", value:160},
        { label: "所羅門群島", value:161},
        { label: "索馬裏", value:162},
        { label: "南非", value:163},
        { label: "西班牙", value:164},
        { label: "斯裏蘭卡", value:165},
        { label: "蘇丹", value:166},
        { label: "蘇裏南", value:167},
        { label: "斯威士蘭", value:168},
        { label: "瑞典", value:169},
        { label: "瑞士", value:170},
        { label: "敘利亞", value:171},
        { label: "塔吉克斯坦", value:172},
        { label: "坦桑尼亞", value:173},
        { label: "多哥", value:175},
        { label: "湯加", value:176},
        { label: "特立尼達和多巴哥", value:177},
        { label: "突尼斯", value:178},
        { label: "土耳其", value:179},
        { label: "土庫曼斯坦", value:180},
        { label: "圖瓦盧", value:181},
        { label: "烏幹達", value:182},
        { label: "烏克蘭", value:183},
        { label: "阿拉伯聯合酋長國", value:184},
        { label: "烏拉圭", value:186},
        { label: "烏茲別克斯坦", value:187},
        { label: "瓦努阿圖", value:188},
        { label: "梵蒂岡城", value:189},
        { label: "委內瑞拉", value:190},
        { label: "也門", value:192},
        { label: "贊比亞", value:193},
        { label: "津巴布韋", value:194}
    ]
};

export var region_opts = {
    "128":{
        en:[
            {label:"No region",value:""},
            {label:"Auckland",value:"AUK"},
            {label:"Northland",value:"NTL"},
            {label:"Waikato",value:"WKO"},
            {label:"Bay of Plenty",value:"BOP"},
            {label:"Gisborne",value:"GIS"},
            {label:"Hawke's Bay",value:"HKB"},
            {label:"Taranaki",value:"TKI"},
            {label:"Manawatu-Wanganui",value:"MWT"},
            {label:"Wellington",value:"WGN"},
            {label:"Tasman",value:"TAS"},
            {label:"Nelson",value:"NSN"},
            {label:"Marlborough",value:"MBH"},
            {label:"West Coast",value:"WTC"},
            {label:"Canterbury",value:"CAN"},
            {label:"Otago",value:"OTA"},
            {label:"Southland",value:"STL"}
        ],
        "zh-CN":[
            {label:"选择所在地区",value: ""},
            {label:"奥克兰",value: "AUK"},
            {label:"北地",value: "NTL"},
            {label:"怀卡托",value: "WKO"},
            {label:"普伦蒂湾",value: "BOP"},
            {label:"吉斯伯恩",value: "GIS"},
            {label:"霍克湾",value: "HKB"},
            {label:"塔拉那基",value: "TKI"},
            {label:"马纳瓦图－旺加努伊",value: "MWT"},
            {label:"惠灵顿",value: "WGN"},
            {label:"塔斯曼",value: "TAS"},
            {label:"纳尔逊",value: "NSN"},
            {label:"马尔伯勒",value: "MBH"},
            {label:"西岸",value: "WTC"},
            {label:"坎特伯雷",value: "CAN"},
            {label:"奥塔哥",value: "OTA"},
            {label:"南地",value: "STL"}
        ],
        "zh-TW":[
            {label:"選擇所在地區",value:""},
            {label:"奧克蘭"   ,value:"AUK"},
            {label:"北地"    ,value:"NTL"},
            {label:"懷卡托"   ,value:"WKO"},
            {label:"普倫蒂灣"  ,value:"BOP"},
            {label:"吉斯伯恩"  ,value:"GIS"},
            {label:"霍克灣"   ,value: "HKB"},
            {label:"塔拉那基"  ,value:"TKI"},
            {label:"馬納瓦圖－旺加努伊"    ,value: "MWT"},
            {label:"惠靈頓"   ,value: "WGN"},
            {label:"塔斯曼"      ,value: "TAS"},
            {label:"納爾遜"      ,value: "NSN"},
            {label:"馬爾伯勒"     ,value: "MBH"},
            {label:"西岸"       ,value: "WTC"},
            {label:"坎特伯雷"     ,value: "CAN"},
            {label:"奧塔哥"      ,value: "OTA"},
            {label:"南地"       ,value: "STL"}
        ]
    },
    "158":{
        en:[
            {label:"Not sure",value: ""},
            {label:"Alexandra",value: "Alexandra"},
            {label:"Aljunied",value: "Aljunied"},
            {label:"Ang Mo Kio",value: "Ang Mo Kio"},
            {label:"Ayer Rajah",value: "Ayer Rajah"},
            {label:"Balestier",value: "Balestier"},
            {label:"Bartley",value: "Bartley"},
            {label:"Bedok",value: "Bedok"},
            {label:"Bishan",value: "Bishan"},
            {label:"Boon Lay",value: "Boon Lay"},
            {label:"Bukit Batok",value: "Bukit Batok"},
            {label:"Bukit Panjang",value: "Bukit Panjang"},
            {label:"Bukit Timah",value: "Bukit Timah"},
            {label:"Buona Vista",value: "Buona Vista"},
            {label:"Changi",value: "Changi"},
            {label:"Chinatown",value: "Chinatown"},
            {label:"Choa Chu Kang",value: "Choa Chu Kang"},
            {label:"Clementi",value: "Clementi"},
            {label:"East Coast",value: "East Coast"},
            {label:"Eunos",value: "Eunos"},
            {label:"Geylang",value: "Geylang"},
            {label:"Hougang",value: "Hougang"},
            {label:"Joo Chiat",value: "Joo Chiat"},
            {label:"Jurong East",value: "Jurong East"},
            {label:"Jurong West",value: "Jurong West"},
            {label:"Kallang",value: "Kallang"},
            {label:"Katong",value: "Katong"},
            {label:"Kembangan",value: "Kembangan"},
            {label:"Kent Ridge",value: "Kent Ridge"},
            {label:"Kim Seng",value: "Kim Seng"},
            {label:"Kranji",value: "Kranji"},
            {label:"Lim Chu Kang",value: "Lim Chu Kang"},
            {label:"Little India",value: "Little India"},
            {label:"Lorong Chuan",value: "Lorong Chuan"},
            {label:"MacPherson",value: "MacPherson"},
            {label:"Mandai",value: "Mandai"},
            {label:"Marina Bay",value: "Marina Bay"},
            {label:"Marine Parade",value: "Marine Parade"},
            {label:"Mount Faber",value: "Mount Faber"},
            {label:"Mount Vernon",value: "Mount Vernon"},
            {label:"Newton",value: "Newton"},
            {label:"Novena",value: "Novena"},
            {label:"Orchard Road",value: "Orchard Road"},
            {label:"Outram",value: "Outram"},
            {label:"Pasir Panjang",value: "Pasir Panjang"},
            {label:"Pasir Ris",value: "Pasir Ris"},
            {label:"Paya Lebar",value: "Paya Lebar"},
            {label:"Pioneer",value: "Pioneer"},
            {label:"Potong Pasir",value: "Potong Pasir"},
            {label:"Punggol",value: "Punggol"},
            {label:"Queenstown",value: "Queenstown"},
            {label:"Raffles Place",value: "Raffles Place"},
            {label:"River Valley",value: "River Valley"},
            {label:"Rochor-Kampong Glam",value: "Rochor-Kampong Glam"},
            {label:"Seletar",value: "Seletar"},
            {label:"Sembawang",value: "Sembawang"},
            {label:"Sengkang",value: "Sengkang"},
            {label:"Senoko",value: "Senoko"},
            {label:"Serangoon",value: "Serangoon"},
            {label:"Siglap",value: "Siglap"},
            {label:"Simpang",value: "Simpang"},
            {label:"Tampines",value: "Tampines"},
            {label:"Tanjong Pagar",value: "Tanjong Pagar"},
            {label:"Telok Blangah",value: "Telok Blangah"},
            {label:"Tengah",value: "Tengah"},
            {label:"Tiong Bahru",value: "Tiong Bahru"},
            {label:"Toa Payoh",value: "Toa Payoh"},
            {label:"Tuas",value: "Tuas"},
            {label:"Ubi",value: "Ubi"},
            {label:"Whampoa",value: "Whampoa"},
            {label:"Woodlands",value: "Woodlands"},
            {label:"Yishun",value: "Yishun"}
        ],
        "zh-CN":[
            {label:"Not sure",value: ""},
            {label:"Alexandra",value: "Alexandra"},
            {label:"Aljunied",value: "Aljunied"},
            {label:"Ang Mo Kio",value: "Ang Mo Kio"},
            {label:"Ayer Rajah",value: "Ayer Rajah"},
            {label:"Balestier",value: "Balestier"},
            {label:"Bartley",value: "Bartley"},
            {label:"Bedok",value: "Bedok"},
            {label:"Bishan",value: "Bishan"},
            {label:"Boon Lay",value: "Boon Lay"},
            {label:"Bukit Batok",value: "Bukit Batok"},
            {label:"Bukit Panjang",value: "Bukit Panjang"},
            {label:"Bukit Timah",value: "Bukit Timah"},
            {label:"Buona Vista",value: "Buona Vista"},
            {label:"Changi",value: "Changi"},
            {label:"Chinatown",value: "Chinatown"},
            {label:"Choa Chu Kang",value: "Choa Chu Kang"},
            {label:"Clementi",value: "Clementi"},
            {label:"East Coast",value: "East Coast"},
            {label:"Eunos",value: "Eunos"},
            {label:"Geylang",value: "Geylang"},
            {label:"Hougang",value: "Hougang"},
            {label:"Joo Chiat",value: "Joo Chiat"},
            {label:"Jurong East",value: "Jurong East"},
            {label:"Jurong West",value: "Jurong West"},
            {label:"Kallang",value: "Kallang"},
            {label:"Katong",value: "Katong"},
            {label:"Kembangan",value: "Kembangan"},
            {label:"Kent Ridge",value: "Kent Ridge"},
            {label:"Kim Seng",value: "Kim Seng"},
            {label:"Kranji",value: "Kranji"},
            {label:"Lim Chu Kang",value: "Lim Chu Kang"},
            {label:"Little India",value: "Little India"},
            {label:"Lorong Chuan",value: "Lorong Chuan"},
            {label:"MacPherson",value: "MacPherson"},
            {label:"Mandai",value: "Mandai"},
            {label:"Marina Bay",value: "Marina Bay"},
            {label:"Marine Parade",value: "Marine Parade"},
            {label:"Mount Faber",value: "Mount Faber"},
            {label:"Mount Vernon",value: "Mount Vernon"},
            {label:"Newton",value: "Newton"},
            {label:"Novena",value: "Novena"},
            {label:"Orchard Road",value: "Orchard Road"},
            {label:"Outram",value: "Outram"},
            {label:"Pasir Panjang",value: "Pasir Panjang"},
            {label:"Pasir Ris",value: "Pasir Ris"},
            {label:"Paya Lebar",value: "Paya Lebar"},
            {label:"Pioneer",value: "Pioneer"},
            {label:"Potong Pasir",value: "Potong Pasir"},
            {label:"Punggol",value: "Punggol"},
            {label:"Queenstown",value: "Queenstown"},
            {label:"Raffles Place",value: "Raffles Place"},
            {label:"River Valley",value: "River Valley"},
            {label:"Rochor-Kampong Glam",value: "Rochor-Kampong Glam"},
            {label:"Seletar",value: "Seletar"},
            {label:"Sembawang",value: "Sembawang"},
            {label:"Sengkang",value: "Sengkang"},
            {label:"Senoko",value: "Senoko"},
            {label:"Serangoon",value: "Serangoon"},
            {label:"Siglap",value: "Siglap"},
            {label:"Simpang",value: "Simpang"},
            {label:"Tampines",value: "Tampines"},
            {label:"Tanjong Pagar",value: "Tanjong Pagar"},
            {label:"Telok Blangah",value: "Telok Blangah"},
            {label:"Tengah",value: "Tengah"},
            {label:"Tiong Bahru",value: "Tiong Bahru"},
            {label:"Toa Payoh",value: "Toa Payoh"},
            {label:"Tuas",value: "Tuas"},
            {label:"Ubi",value: "Ubi"},
            {label:"Whampoa",value: "Whampoa"},
            {label:"Woodlands",value: "Woodlands"},
            {label:"Yishun",value: "Yishun"}
        ],
        "zh-TW":[
            {label:"Not sure",value: ""},
            {label:"Alexandra",value: "Alexandra"},
            {label:"Aljunied",value: "Aljunied"},
            {label:"Ang Mo Kio",value: "Ang Mo Kio"},
            {label:"Ayer Rajah",value: "Ayer Rajah"},
            {label:"Balestier",value: "Balestier"},
            {label:"Bartley",value: "Bartley"},
            {label:"Bedok",value: "Bedok"},
            {label:"Bishan",value: "Bishan"},
            {label:"Boon Lay",value: "Boon Lay"},
            {label:"Bukit Batok",value: "Bukit Batok"},
            {label:"Bukit Panjang",value: "Bukit Panjang"},
            {label:"Bukit Timah",value: "Bukit Timah"},
            {label:"Buona Vista",value: "Buona Vista"},
            {label:"Changi",value: "Changi"},
            {label:"Chinatown",value: "Chinatown"},
            {label:"Choa Chu Kang",value: "Choa Chu Kang"},
            {label:"Clementi",value: "Clementi"},
            {label:"East Coast",value: "East Coast"},
            {label:"Eunos",value: "Eunos"},
            {label:"Geylang",value: "Geylang"},
            {label:"Hougang",value: "Hougang"},
            {label:"Joo Chiat",value: "Joo Chiat"},
            {label:"Jurong East",value: "Jurong East"},
            {label:"Jurong West",value: "Jurong West"},
            {label:"Kallang",value: "Kallang"},
            {label:"Katong",value: "Katong"},
            {label:"Kembangan",value: "Kembangan"},
            {label:"Kent Ridge",value: "Kent Ridge"},
            {label:"Kim Seng",value: "Kim Seng"},
            {label:"Kranji",value: "Kranji"},
            {label:"Lim Chu Kang",value: "Lim Chu Kang"},
            {label:"Little India",value: "Little India"},
            {label:"Lorong Chuan",value: "Lorong Chuan"},
            {label:"MacPherson",value: "MacPherson"},
            {label:"Mandai",value: "Mandai"},
            {label:"Marina Bay",value: "Marina Bay"},
            {label:"Marine Parade",value: "Marine Parade"},
            {label:"Mount Faber",value: "Mount Faber"},
            {label:"Mount Vernon",value: "Mount Vernon"},
            {label:"Newton",value: "Newton"},
            {label:"Novena",value: "Novena"},
            {label:"Orchard Road",value: "Orchard Road"},
            {label:"Outram",value: "Outram"},
            {label:"Pasir Panjang",value: "Pasir Panjang"},
            {label:"Pasir Ris",value: "Pasir Ris"},
            {label:"Paya Lebar",value: "Paya Lebar"},
            {label:"Pioneer",value: "Pioneer"},
            {label:"Potong Pasir",value: "Potong Pasir"},
            {label:"Punggol",value: "Punggol"},
            {label:"Queenstown",value: "Queenstown"},
            {label:"Raffles Place",value: "Raffles Place"},
            {label:"River Valley",value: "River Valley"},
            {label:"Rochor-Kampong Glam",value: "Rochor-Kampong Glam"},
            {label:"Seletar",value: "Seletar"},
            {label:"Sembawang",value: "Sembawang"},
            {label:"Sengkang",value: "Sengkang"},
            {label:"Senoko",value: "Senoko"},
            {label:"Serangoon",value: "Serangoon"},
            {label:"Siglap",value: "Siglap"},
            {label:"Simpang",value: "Simpang"},
            {label:"Tampines",value: "Tampines"},
            {label:"Tanjong Pagar",value: "Tanjong Pagar"},
            {label:"Telok Blangah",value: "Telok Blangah"},
            {label:"Tengah",value: "Tengah"},
            {label:"Tiong Bahru",value: "Tiong Bahru"},
            {label:"Toa Payoh",value: "Toa Payoh"},
            {label:"Tuas",value: "Tuas"},
            {label:"Ubi",value: "Ubi"},
            {label:"Whampoa",value: "Whampoa"},
            {label:"Woodlands",value: "Woodlands"},
            {label:"Yishun",value: "Yishun"}
        ]
    }
};

export var timeZone_opts = [
];
